$ErrorActionPreference='Stop'
$dir='D:\Git\Book\整理中\1_原文校对\ad'
$F=[IO.File]::ReadAllLines("$dir\2_female.tex")
$P=[IO.File]::ReadAllLines("$dir\3_position.tex")
function Idx($arr,$pat,$start){ for($i=$start;$i -lt $arr.Count;$i++){ if(([string]$arr[$i]) -match $pat){ return $i } }; throw ("NOT FOUND: "+$pat) }
$iSecNei  = Idx $F '^\s*\\section\{内生殖器\}' 0
$iYin     = Idx $F '^\s*\\subsection\{阴道\}\s*$' $iSecNei
$iSpill   = Idx $F '口交相关卫生与技巧' $iYin
$iCervixA = Idx $F '子宫的颈部就是子宫颈' 0
$iGA      = Idx $F '格雷芬伯格' $iCervixA
$iUterA   = Idx $F '^\s*\\subparagraph\{解剖结构\}' $iGA
$iTubA    = Idx $F '^\s*\\subparagraph\{解剖结构\}' ($iUterA+1)
$iOvaA    = Idx $F '^\s*\\subparagraph\{解剖结构\}' ($iTubA+1)
$iHorA    = Idx $F '性激素是一种化学物质' 0
$iNote    = Idx $F '^\s*%\s*注（r80）' 0
$iH110    = Idx $F '^\s*\\subsection\{阴道的结构与功能\}' 0
$iG       = Idx $F '^\s*\\subsection\{G点与前壁敏感区\}' 0
$iGongB   = Idx $F '^\s*\\subsection\{子宫的结构与周期\}' 0
$iOvaB    = Idx $F '^\s*\\subsection\{卵巢的排卵与激素\}' 0
$iTubB    = Idx $F '^\s*\\subsection\{输卵管\}' 0
$iOvaC    = Idx $F '^\s*\\subsubsection\{卵巢\}' 0
$iTubC    = Idx $F '^\s*\\subsubsection\{输卵管\}' 0
$iUterC   = Idx $F '^\s*\\subsubsection\{子宫\}' 0
$iVagC    = Idx $F '^\s*\\subsubsection\{阴道\}' 0
$iBrast   = Idx $F '^\s*\\section\{乳房\}' 0
$iRujSpill= Idx $F '^\s*\\textbf\{二十、乳交技巧与体验\}' 0
$iMoved   = Idx $F '已移出.*阴交技巧与体验' 0
$iPRuj  = Idx $P '^\s*\\section\{乳交\}' 0
$iPSugu = Idx $P '^\s*\\section\{素股' 0
$names=@('secNei','yin','spill','cervixA','GA','uterA','tubA','ovaA','horA','note','h110','G','gongB','ovaB','tubB','ovaC','tubC','uterC','vagC','brast','rujSpill','moved')
$vals=@($iSecNei,$iYin,$iSpill,$iCervixA,$iGA,$iUterA,$iTubA,$iOvaA,$iHorA,$iNote,$iH110,$iG,$iGongB,$iOvaB,$iTubB,$iOvaC,$iTubC,$iUterC,$iVagC,$iBrast,$iRujSpill,$iMoved)
for($k=0;$k -lt $vals.Count;$k++){ Write-Host (($vals[$k]+1).ToString().PadLeft(6) + "  " + $names[$k] + "  |" + ([string]$F[$vals[$k]]).Trim() + "|") }
Write-Host ("      P pRuj=" + ($iPRuj+1) + " |" + ([string]$P[$iPRuj]).Trim() + "|")
Write-Host ("      P pSugu=" + ($iPSugu+1) + " |" + ([string]$P[$iPSugu]).Trim() + "|")
Write-Host ("F count=" + $F.Count + " P count=" + $P.Count)
